### ISSUE TITLE
Current Design is commercial

### ISSUE THREAD

**Issue by fettlaus** [JZ6/PoGoMap#26]
I neither speak norwegian nor do I own the domain, but it looks like you used a design created by http://www.100art.no/

I don't know if you officially bought the design so i just wanted to inform you, that it possibly is a commercial one. Please correct me if I am wrong. I only found out about this because I wanted to use your design myself. Changed my mind about that for now.

**Comment by vintagesucks** [comment]
- http://tympanus.net/codrops/2015/03/12/freebie-forkio-one-page-website-template/
- http://tympanus.net/codrops/licensing/

tl;dr
The resources on Codrops can be used freely in personal and commercial projects.

**Comment by fettlaus** [comment]
Ignore my comment then. Thanks for providing the link!
